# System
alias upgrade='sudo apt update && sudo apt -y upgrade'
alias aliases='editor ~/.bash_aliases'
alias aliases-cat='cat ~/.bash_aliases'
alias count-lines='ls -1 | wc -l'
alias psa='ps aux | grep'

# Tar
alias tarcompress='tar -zcvf'
alias tarextract='tar -zxvf'

# Git
alias gs='git status'
alias ga='git add'
alias gr='git restore'
alias grs='gr --staged'
alias gc='git commit'
alias gca='gc --amend --no-edit'
alias gl='git lg'
alias gb='git branch'
alias gco='git checkout'
alias gfo='git fetch origin'
alias gpo='git pull origin'
alias gpcb='gpo $(git rev-parse --abbrev-ref HEAD)'
alias gpomain='gco main && gpo main'
alias gp='git push -u'

# Docker
alias dk='docker'
alias psc='dk ps --all'
alias psi='dk image ls'
alias psv='dk volume ls'
alias psd='psc && echo && psi && echo && psv'
alias dc='dk compose'
alias dcb='dc build'
alias dcu='dc up'
alias dcs='dc stop'
alias dce='dc exec'

# Rails
# alias rails='bin/rails'
alias dbmigrate='rails db:migrate db:test:prepare'
alias dbrollback='rails db:rollback db:test:prepare'
alias dbmigback='rails db:migrate db:rollback'
alias rs='rails server'
alias rc='rails console'
alias be='bundle exec'
alias rspec='be rspec'
alias sidekiq='be sidekiq'

# Rails on Docker
#alias dcer='dce rails'
#alias drails='dcer bin/rails'
#alias dsetup='dcer bin/setup'
#alias ddev='dcer bin/dev'
#alias dbash='dcer /bin/bash'
#alias bundle='dcer bundle'
#alias rspec='dcer rspec'
#alias sidekiq='dcer sidekiq -q default'
#alias dbseed='drails db:seed'
#alias dbmigrate='drails db:migrate db:test:prepare'
#alias dbrollback='drails db:rollback db:test:prepare'
#alias dbforback='drails db:migrate db:rollback'
#alias dbreset='drails db:reset db:test:prepare'
#alias cleanup='drails log:clear tmp:clear'
#alias rs='drails server -b 0.0.0.0'
#alias rc='drails console'
#alias psql='dbash -c "psql -h postgres -U postgres -W"'
